 const GET_ALL_RECIPE = "GET_ALL_RECIPE"
 const GET_DIETS = "GET_DIETS"
 const FILTER_RECIPE = "FILTER_RECIPE"
 const ORDERBYHS ="ORDERBYHS"
 const ORDERNAME = "ONRDERNAME"
 const DELETE_RECIPE ="DELETE_RECIPE"
 const FIILTER_DIET_AIP = "FIILTER_DIET_AIP"

 module.exports = { FIILTER_DIET_AIP, GET_ALL_RECIPE, GET_DIETS, FILTER_RECIPE, ORDERBYHS, ORDERNAME,DELETE_RECIPE }